image: debian/stable
packages:
  - composer
  - unzip
  - php-curl
  - php-dom
  - php-date
  - php-mbstring
sources:
  -  https://git.sr.ht/~fkooman/vpn-server-node
tasks:
  - setup: |
      cd vpn-server-node
      composer update
  - build: |
      cd vpn-server-node
      vendor/bin/phpunit
